
CREATE TABLE PRICES(ID SERIAL NOT NULL,BRAND_ID INTEGER, START_DATE TIMESTAMP, END_DATE TIMESTAMP, PRICE_LIST INTEGER, PRODUCT_ID INTEGER, PRIORITY INTEGER, PRICE DECIMAL(10,2), CURR VARCHAR(3),PRIMARY KEY (ID));
